# Generated by Django 3.1.6 on 2021-02-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_title', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=10000)),
                ('year', models.CharField(max_length=10000)),
                ('genre', models.CharField(max_length=10000)),
                ('country', models.CharField(max_length=10000)),
                ('budget', models.CharField(max_length=10000)),
                ('duration', models.IntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Film_with_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_in_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.film')),
            ],
        ),
    ]
