# Generated by Django 3.1.6 on 2021-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film_with_user',
            old_name='skill_in_category',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='film_with_user',
            old_name='main_category',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
